orm:
  connections:
    Default:
      username: root
      password: 123
      database: orm
      host: 127.0.0.1
      handler: Tyutnev\SavannaOrm\Type\MySQL
  default_connection: Default

  entity_directory: src/Entity
